[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
dotenv = "0.15.0"
itertools = "0.14.0"
nom = "8.0.0"
regex = "1.12.2"
reqwest = {version = "0.12.24", features = ["blocking"]}
